### ISSUE TITLE
Fix blog display and sorting

### ISSUE THREAD

**Issue by ddkapan** [wildliferesilience/wildliferesilience#19]
Fix the blog to have the following:

- [x]  informative titles on the highlights page
- [x] and REVERSE sorting by date (really important)
- [x] display the date (allow hard coding) 

Right now the overall highlights page doesn't give a date, the titles are being sorted alphabetically, and changing them to YYYY-MM-DD format just makes them sort oldest to newest (which is backward).  Since we are 'post-pending' information we should be able to display a hard-coded date in the blog table.  See the three examples.
Thanks!
Durrell

**Comment by mschulist** [comment]
change the `sort: "date asc"` in `highlights.qmd` and the dates in the yml header in each posts
