### ISSUE TITLE
Reference for the resilience figure on index.qmd is missing

### ISSUE THREAD

**Issue by ddkapan** [wildliferesilience/wildliferesilience#22]
- [ ] Establish why we are missing this reference -- @mschulist please check to see if you fast-forwarded development branches correctly before we merged pull requests
- [ ] Restore missing reference: Roopnarine, P. D, and Angielczyk, K. D.
- [ ] Double-check we have other changes up to the loss of the reference

**Comment by mschulist** [comment]
just updated it. You can always use git blame to see when a line has changed and who changed it
