### ISSUE TITLE
Finalize full list of main pages

### ISSUE THREAD

**Issue by ddkapan** [wildliferesilience/wildliferesilience#24]
Let's discuss the appropriate number of 'top-level' pages to get the story across:

- currently, we have: Resilience, Foodwebs, Study Area, Highlights, Resources, About
- consider: Home (an overview), Resilience, Biodiversity, Foodwebs, Study Area, Metrics, Highlights, Resources, About
Or the ideal combination of the latter either across the top of for instance, under Resilience (several topics), Under Biodiversity (several issues including foodwebs), Under a 'methods' section Study Area, Metrics, etc...

**Comment by ddkapan** [comment]
We can follow this resource, if we want fewer, longer pages we can do the sidebar thing: [website nav](https://quarto.org/docs/websites/website-navigation.html)

**Comment by ddkapan** [comment]
After our meeting today with Dr. Roopnarine we decided to try out the following across the top:

Home Resilience Biodiversity Foodweb Metrics Study Area Highlights Resources About

So we need to 

- [ ] modify the YAML to point to those pages in that order

and add the following pages:

- [ ] Home
- [ ] Metrics

Creating a branch for this issue...

**Comment by mschulist** [comment]
@ddkapan Take a look at the home page on this branch and see if that looks good. When people over over the image, it will show some text that explains the page the image links to. I couldn't get the tiff to have a transparent background, but I'll work on that soon. We also need to get some better icons for the pages.

**Comment by ddkapan** [comment]
@mschulist after reviewing the biodiversity.qmd pull request, the last thing todo on the page creation issue is 'metrics'.  Can you please create the 'metrics.qmd' on a branch and move the metrics bit from foodwebs to the new metrics page?

**Comment by ddkapan** [comment]
Only 1-more thing.  Give home a home on the top and dropdowns, for more information see the Google notes: [https://docs.google.com/document/d/1w9UdvHAB8oDUtJMfcovYL68pZRlMTuYLtTJOqClB76Q/edit](wildliferesilience WEBSITE RESOURCES)

#2023-08-11  List of further ‘to-do’s’ (may overlap with below)

**Comment by ddkapan** [comment]
This is finished
